### ISSUE TITLE
Error with permissions

### ISSUE THREAD

**Issue by cmarquezrusso** [dmitry-zaets/vagrantfile-windows-iis-mssql#1]
```
default: Running: vagrant-scripts/setup-permissions-for-website-folder.ps1 as c:\tmp\vagrant-shell.ps1
```

==> default: Setting up access to folder
==> default: C:\test-website: The system cannot find the file specified.
==> default: Successfully processed 0 files; Failed processing 1 files
![screen shot 2015-05-25 at 12 35 37 pm](https://cloud.githubusercontent.com/assets/521587/7790411/e0120756-02da-11e5-8c1b-819e10b43ed4.png)

**Comment by dmitry-zaets** [comment]
I'm currently working on this issue.
New idea was to use rsync to sync folders continuously, that also should fix permissions issue.

**Comment by dmitry-zaets** [comment]
Reverted previous version. Solved.
