### ISSUE TITLE
Port 85 is not working on OS X 

### ISSUE THREAD

**Issue by cmarquezrusso** [dmitry-zaets/vagrantfile-windows-iis-mssql#2]
As it is a restricted port, this box is not working on OS X without root permissions. My suggest is to change it to another port. 1080 Works correctly
![screen shot 2015-05-25 at 12 41 51 pm](https://cloud.githubusercontent.com/assets/521587/7790429/84499ff0-02db-11e5-9186-c48093013938.png)

![screen shot 2015-05-25 at 12 40 45 pm](https://cloud.githubusercontent.com/assets/521587/7790423/6119615a-02db-11e5-8612-9fe178dde110.png)

**Comment by dmitry-zaets** [comment]
Fixed with 1a7bb3d26c1935339004fa25aca234ba304d4321
