### ISSUE TITLE
Two web folders

### ISSUE THREAD

**Issue by cmarquezrusso** [dmitry-zaets/vagrantfile-windows-iis-mssql#3]
There are two folders for the same purpose: Web app data. This will get some issues with some users. My suggestion is to use one and delete the other one.
![screen shot 2015-05-25 at 12 43 45 pm](https://cloud.githubusercontent.com/assets/521587/7790432/b926b834-02db-11e5-9f9f-b70579bca52b.png)

**Comment by dmitry-zaets** [comment]
Thanks! Removed.
